- name: mjpg-stream setup
  hosts:
  - pogoplug2b
  - pogoplug2a
  gather_facts: false
  sudo: true
  tasks:
  #- pacman: name=aria2 state=installed

  #- pacman: name=apache state=installed
  
  - template: src=templates/etc_systemd_system_aria2.service dest=/etc/systemd/system/aria2.service owner=root group=root

  - template: src=templates/etc_systemd_system_aria2.conf dest=/etc/systemd/system/aria2.conf owner=root group=root

  - file: path=/usr/local/appscript owner=root group=root state=directory

  - template: src=templates/usr_local_appscript_aria2.sh dest=/usr/local/appscript/aria2.sh owner=root group=root mode=0755

  - command: systemctl enable aria2
